version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sabai_class
      MYSQL_USER: sabai_class
      MYSQL_PASSWORD: XsOC7X06TB
    ports:
      - "13306:3306"